version: '3.3'

services:

  gogs-postgres:
    image: postgres:15
    container_name: gogs-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
      - POSTGRES_DB=gogs
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - red1

  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "10022:22"
    links:
      - gogs-postgres
    environment:
      - TZ="Europe/Madrid"
    volumes:
      - ./gogs-data:/data
      - ./config/gogs:/data/gogs/conf
    depends_on:
      - gogs-postgres
    networks:
      - red1

  gocd-server:
    image: gocd/gocd-server:v23.5.0
    container_name: gocd-server
    restart: unless-stopped
    ports:
      - "8153:8153"
    networks:
      - red1

  gocd-agent:
    image: gocd/gocd-agent-alpine-3.16:v23.5.0
    container_name: gocd-agent
    restart: unless-stopped
    environment:
      - GO_SERVER_URL=http://gocd-server:8153/go
    networks:
      - red1
    depends_on:
      - gocd-server

networks:
  red1:
    driver: bridge
